#! /usr/bin/env bash

rm .env
put()(echo "${1}" >> .env)

#user=$(cat < ./debug/remote.conf | grep USER_NAME | cut -d'=' -f2)
#user_uid=$(id -u ${user})
#user_gid=$(id -g ${user})

version="${1:-1.0.beta.16}"
user=develop
user_uid=5001
user_gid=5001

put "NAME=${user}"
put "UID=${user_uid}"
put "GID=${user_gid}"
put "TZ=Europe/Moscow"
put "VERSION=${version}"

#dock
#docker image prune -f
#docker-compose build
docker-compose up --build -d
#docker run -it kvas_develop /bin/bash
#docker run --user 5001:5001 -it kvas_develop /bin/bash
#docker exec --user 5001:5001 -it kvas_debian_10 /bin/bash
