#! /usr/bin/env bash

rm .env
put()(echo "${1}" >> .env)

#user=$(cat < ./debug/remote.conf | grep USER_NAME | cut -d'=' -f2)
#user_uid=$(id -u ${user})
#user_gid=$(id -g ${user})

version="${1:-1.0.beta.16}"
user=develop
user_uid=5001
user_gid=5001
DEBUG=NO

put "NAME=${user}"
put "UID=${user_uid}"
put "GID=${user_gid}"
put "TZ=Europe/Moscow"
put "VERSION=${version}"
put "DEBUG=${DEBUG}"

# Если уже создан образ kvas_develop
docker container prune -f
if ! docker ps -a -f 'status=running' | grep -q kvas ; then
#	то заходим внуть контейнера kvas_develop и сразу запускаем соборку пакета
#	если не создан образ, то запускаем сборку образа
	docker-compose up --build -d
fi
# Запускаем контейнер и срузу запускаем сборку пакета
docker run --user 5001:5001 -it kvas_develop /apps/kvas/build/make_app.run /bin/bash
