#!/bin/bash

lib_load=". /opt/apps/kvas/bin/libs/vpn"

on_server(){
	APP_REMOTE_FILE="../../debug/remote.conf"
	MY_PORT=$(cat < "${APP_REMOTE_FILE}" | grep -E '^PORT' | cut -d' ' -f3 | cut -d"=" -f2)
	MY_ROUTER=$(cat < "${APP_REMOTE_FILE}" | grep -E '^ROUTER' | cut -d'"' -f2| cut -d"=" -f2)
	cmd="${1}"
	ssh "${MY_ROUTER}" -p "${MY_PORT}" "${cmd}"
}

print_on_error(){
	status=${1}; output=${2}
	# 	в случае ошибок в тесте - будет вывод основных критериев работы
	echo "status=${status}"
	echo "output=${output}"
}

print_line(){
	length=${1:-100};
	printf '%0.s=' $(seq 1 ${length})
	printf '\n'
}

header() {
	print_line
	echo ${1}
	print_line
}