#!/bin/bash
source ./tests_lib

cd "./bats/" || exit 1

header "ПРОВЕРКА НАЛИЧИЯ ОСНОВНЫХ ФАЙЛОВ ИЗ БИБЛИОТЕКИ КВАСА"
./start.bats
echo

header "ПРОВЕРКА РАБОТЫ БЛОКА VPN ПРАВИЛ КВАСа"
./vpn_ipv6.bats
echo

header "ПРОВЕРКА РАБОТЫ ФУНКЦИЙ ИЗ ОБЩЕЙ БИБЛИОТЕКИ КВАСА"
./func.bats
echo

header "ПРОВЕРКА РАБОТЫ ФУНКЦИЙ ОПРЕДЕЛЕНИЯ АДРЕСОВ И ДОМЕННЫХ ИМЕН"
./hosts.bats
echo

header "ПРОВЕРКА РАБОТЫ БЛОКА БЛОКИРОВКИ РЕКЛАМЫ"
./ads.bats
echo

header "ПРОВЕРКА РАБОТЫ БЛОКА ОБНОВЛЕНИЯ ПРАВИЛ КВАСа"
./cron.bats
echo