#!/bin/sh

if [ "${1}" = "stop" ] ; then
	. /opt/apps/kvas/bin/libs/route
	log_error "Интернет соединение ${interface} прервано. Восстанавливаем доступ к сети: ip=${address}, mask=${mask}, gw=${gateway}."
	ip4_up_net_default "${interface}" "${address}" "${mask}" "${gateway}"
	exit 0
else
	exit 1
fi


