#!/bin/sh

#------------------------------------------------------------------------------
#
#	ПАКЕТ КВАС
#
#------------------------------------------------------------------------------
#
#	Данный файл служит для начального запуска пакета квас при загрузке системы
#	https://github.com/ndmsystems/packages/wiki/Opkg-Component с командой start
#	основными задачами являются:
#
#	1. Создание таблицы ipset ip4
#	2. Загрузка таблицы ipset доменными именами
#
# ------------------------------------------------------------------------------
#	Разработчик: mail@zeleza.ru
#	Дата создания: 21/05/2022
#	Лицензия: Apache License 2.0
# ------------------------------------------------------------------------------

case ${1} in
	start|restart)
		. /opt/apps/kvas/bin/libs/vpn
		cmd_kvas_init
		if has_ssr_enable; then
			while /opt/etc/init.d/S22shadowsocks status | grep -q dead
			do
				/opt/etc/init.d/S22shadowsocks restart
				sleep 2
			done
		fi
	;;
esac
