#!/bin/sh 

ENABLED=yes
PROCS=/opt/sbin/xray
ARGS=" run -config /opt/etc/xray/vless.json "
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
