#!/bin/sh
#------------------------------------------------------------------------------
#	ПАКЕТ КВАС
#------------------------------------------------------------------------------
#
#	Данный файл служит для запуска AdguardHome соместно с пакетом КВАС
#	1. Создает новую таблицу ipset под названием unblock
#	2. Обновляет таблицу ipset данными из файла с доменными именами, IP и сетями
#
#	Файл содержит основные аргументы запуска AdguardHome,
#	основные из которых являются:
#	1. Файл конфигурации
#	2. Файл журналирования
#	3. Папка из которой запускается пакет
#
# ------------------------------------------------------------------------------
#	Разработчик: mail@zeleza.ru
#	Дата создания: 21/05/2022
#	Лицензия: Apache License 2.0
# ------------------------------------------------------------------------------

CNF="-c /opt/etc/AdGuardHome/AdGuardHome.yaml"
DIR="-w /opt/etc/AdGuardHome"
LOG="-l /opt/var/log/AdGuardHome.log"
PID="--pidfile /opt/var/run/AdGuardHome.pid"
UPD="--no-check-update"
OPT="${DIR} ${LOG} ${PID} ${UPD} ${CNF}"

ENABLED=yes
PROCS=AdGuardHome
ARGS="${OPT}"
PREARGS=""
DESC=${PROCS}
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
case ${1} in
        start|restart)
                . /opt/apps/kvas/bin/libs/vpn
                cmd_kvas_init initd
                iptables_reset &> /dev/null
                ready "Перезапускаем AdGuardHome"
                . /opt/etc/init.d/rc.func &>/dev/null
                if [ $? = 0 ]; then when_ok "ГОТОВО"; else when_bad "ОШИБКА"; fi
                print_line
        ;;

        *)
                . /opt/etc/init.d/rc.func
        ;;
esac


