#!/bin/sh
[ "${type}" = "iptables" ] || exit 0
#[ "${table}" = "nat" ] || exit 0

# Shadowsocks+
if ! /opt/sbin/iptables-save 2>/dev/null | grep unblock | grep -q @PROXY_PORT ; then
	ipset create unblock hash:net family inet -exist
	/opt/sbin/iptables -w -t nat -A PREROUTING -i @INFACE -p tcp -m set --match-set unblock dst -j REDIRECT --to-port @PROXY_PORT
fi

exit 0
