#!/bin/sh

[ "${type}" = "iptables" ] || exit 0
#[ "${table}" = "mangle" ] || exit 0

#ip4t() { if ! iptables -C "$@" &>/dev/null; then iptables -A "$@"; fi }

if ! iptables-save | grep -q CONNMARK ; then
	# VPN
	ipset create unblock hash:net family inet -exist
	# Без отключения ускорителей
	iptables -A PREROUTING -t mangle -m conntrack --ctstate NEW -m set --match-set unblock dst -j CONNMARK --set-mark 0xd1000
	iptables -A PREROUTING -t mangle -j CONNMARK --restore-mark
fi
exit 0