#!/bin/sh


#------------------------------------------------------------------------------
#
#	ПАКЕТ КВАС
#
#------------------------------------------------------------------------------
#
#	Данный файл служит для создания правил для пропуска Shadowsocks трафика (tcp)
#	при использовании любого shadowsocks подключения.
#	Они срабатывают при перезаписи правил в таблице netfilter
#	https://github.com/ndmsystems/packages/wiki/Opkg-Component
#
# ------------------------------------------------------------------------------
#	Разработчик: mail@zeleza.ru
#	Дата создания: 21/05/2022
#	Лицензия: Apache License 2.0
# ------------------------------------------------------------------------------

# Shadowsocks+
if [ "${type}" = "iptables" ] && echo "${table}" | grep -qE 'nat|mangle' ; then

	. /opt/apps/kvas/bin/libs/ndm
	proxy_port=$(get_config_value SSR_DNS_PORT)
	interface=$(get_local_inface)
	if ! ip4save | grep "${SSR_IPTABLES_CHAIN}" | grep -qv '\[0:0\]' && \
   	   ! ip4save | grep PREROUTING | grep "${interface}" | grep "${table_name}" | grep REDIRECT | grep -q "${proxy_port}" ; then
#   		logger -t "КВАС"  "Запущен файл ${0}"
	#	 создаем правила для shadowsocks подключения
		ip4_firewall_ssr_prune &> /dev/null
		ip4_firewall_set_ssr_rules &> /dev/null
		ip4_add_guest_to_ssr_network &> /dev/null
	fi

fi




