#!/bin/sh

TABLE_ID=1001
PRIORITY=1778
INFACE_VPN=@ENTWARE_INFACE_NAME
INFACE_GW4=$(ip addr show ${INFACE_VPN} | grep -Po "(?<=inet ).*(?=/)")

ip4() (/opt/sbin/ip -4 "$@")
ip4tables() (if ! /opt/sbin/iptables -C "$@" &>/dev/null; then iptables -A "$@"; fi)

logger "Создаем правила iptables для ipset для маршрутизации записей в таблице unblock"
ip4tables PREROUTING -t mangle -m conntrack --ctstate NEW -m set --match-set unblock dst -j CONNMARK --set-mark 0xd1000
ip4tables PREROUTING -t mangle -j CONNMARK --restore-mark
logger "unblock::Таблица ipset ID#${TABLE_ID} создана"
logger "Правила для unblock настроены."

logger "unblock::Поднимаем ${INFACE_CLI} интерфейс"
ip4 route add table ${TABLE_ID} default via ${INFACE_GW4} dev ${INFACE_ENT} 2>/dev/null
ip4 route show table main |grep -Ev ^default | while read -r ROUTE; do ip4 route add table ${TABLE_ID} ${ROUTE} 2>/dev/null; done
logger "unblock::Устанавливаем приоритет таблицы ID#${TABLE_ID} в значение ${PRIORITY}"
ip4 rule add fwmark 0xd1000 lookup ${TABLE_ID} priority ${PRIORITY} 2>/dev/null
ip4 route flush cache
logger "unblock::DNS кэш очищен."
logger "unblock::Таблица ID#${TABLE_ID} создана"




