#!/bin/sh
. /opt/apps/kvas/bin/libs/ndm

[ "${1}" = "hook" ] && \
[ "${change}" = "link" ] && \
[ "${id}" = "${INFACE_CLI}" ] && {

	case "${id}-${change}-${connected}-${link}-${up}" in
    "${id}-link-no-down-down" )
		ip4_rule_del_priority
    ;;
    "${id}-link-yes-up-up" )
		ip4_add_route_table
		ip4_rule_set_priority
    ;;
	esac

	exit 0
}

